### ISSUE TITLE
Unhandled Rejection causes coin selection to hang

### ISSUE THREAD

**Issue by n41r0j** [buildog/BarterDEX#64]
```
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'map' of undefined
    at /Users/n41r0j/BarterDEX/webpack:/api.js:214:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7) } reason: TypeError: Cannot read property 'map' of undefined
    at /Users/n41r0j/BarterDEX/webpack:/api.js:214:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
endpoint bot_list failed
{ Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
```

These messages appear shortly after I click a coin in the main menu. The black/white balls keep turning, the Electrum label appears, but no change of screen. I can  work around this, by first clicking on a coin with native wallet enabled, going back and click the former coin again. That leads me in the orderbook screen, but as already mentioned, orderbooks are not visible yet.

**Comment by buildog** [comment]
we have implemented a retry in case endpoint fail to respond.
